export * from "./product"
export * from "./carTypes"
export * from "./category"
export * from "./authTypes"
export * from "./carMaker"
export * from "./generalTypes"
export * from "./productTypes"
export * from "./serviceTypes"
export * from "./serviceStatusTypes"
export * from "./serviceFeesTypes"
export * from "./productSoldTypes"

// export * from "./productModel"
// export * from "./productYear"
// export * from "./productBrand"
// export * from "./productType"
